### PR TITLE
Root cleanup

### PR DESCRIPTION
**Pull request by sneikki**
- Remove unnecessary files left at project root (package.json, package-lock.json)
- Add .editorconfig to represent source files more consistently among various platforms
- Update root & child gitignores
- Migarate nvmrc to client and server

### CODE REVIEW

**Comment by JVS23** [comment]
The workflow doesn't seem to recognize the working directories, error from GitHub actions:

"The workflow is not valid. .github/workflows/lint.yml (Line: 20, Col: 9): Unexpected value 'working-directory' .github/workflows/lint.yml (Line: 34, Col: 9): Unexpected value 'working-directory'"

**Comment by JVS23** [comment]
Looks like it doesn't have the dependency lock files in the ./client and ./server folders, with them it'll start working with the latest commit fix.

**Comment by sneikki** [comment]
They did work when I ran the workflow locally. It succeeds locally with the most recent commits as well. However, GH still fails. I'll try to find a solution.

**Comment by sneikki** [comment]
It required specifying both the location of package-lock.json as npm's cache dependency path, and that default working directory fix.

**Review by JVS23 — APPROVED** [review]
Nice, good fix!

**Pull request merged**
