### PR TITLE
Client refactoring

### PR DESCRIPTION
**Pull request by sneikki**
- Refactor code here and there
- Create directory for view components
- Extract text field component from existing hard-coded text fields
- Create a custom hook for text fields to simplify their use
- Add interactivity to styling of text fields
- Change some styles to better match the UI design
- Convert UserService to a class
- Create ConfigService

### CODE REVIEW

**Comment by sneikki** [comment]
Oho tää vähän paisu :D aamuja lukemiseen

**Comment by sneikki** [comment]
Tai itse asiassa suljen tän ja teen useemman pienen :D

**Comment by sneikki** [comment]
Closed as too large.

**Comment by sneikki** [comment]
Virhe ei suljetakaan :D

**Review by JVS23 — APPROVED** [review]
LGTM

**Pull request merged**
